var api="http://localhost:8118";
var poolHost="testnet.xtlpool.com";
var email="support@xtlpool.com";
var telegram="";
var discord="https://discord.gg/zng9k2D";
var marketCurrencies=["{symbol}-BTC","{symbol}-USD","{symbol}-EUR","{symbol}-CAD"];
var blockchainExplorer="https://testexplorer.stellite.cash/search?value={id}";
var transactionExplorer="https://testexplorer.stellite.cash/search?value={id}";
var themeCss="themes/stellite.css";
